<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Version>0.1.0</Version>
        <DocumentsSigningKeyPath Condition="'$(DocumentsSigningKeyPath)' == ''"
            >$(MSBuildThisFileDirectory).local/development.snk</DocumentsSigningKeyPath>
    </PropertyGroup>
</Project>
